config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 
  
  resources :students
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
    def index
        @students = Student.all
    end
    
    def new
        @students = Student.new
      end

      def create
        students = Student.new(student_params)
        if students.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @Students = Student.find(params[:id])
      end
    
      private
      def student_params
        params.require(:student).permit(:body)
      end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    def index
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
GeekKobebe

<%= link_to "新規投稿ページへ",  :controller => "students", :action => "new" %>

<h1>GeekTwitter</h1>
<h3>Tweet一覧</h3>
<%= link_to "新規投稿へ", "students", :action => "new" %>
<div class="students-container">
  <% @students.each do |t| %>
  <div class="student">
    <%= t.body %>
    <%= t.created_at %>
     #追記始め
    <%= link_to "詳細へ", student_path(t.id) %>
　　 #追記終わり
  </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>GeekSalon</h1>
<h3>新規Tweet</h3>
<%= form_for @students do |f| %>
  <div class="field">
    <%= f.label :Tweet %>
    <%= f.text_field :name, :size => 140 %>
  </div>


  <%= f.submit "Tweetする" %>
<% end %>

<%= link_to "Tweet一覧に戻る", students_path %>

app/views/students/show.html.erb
<h1>GeekKobe</h1>
<h3>Tweet詳細</h3>
<div class="student">
  <p><%= @student.body %></p>
  <p><%= @tweet一覧に戻る", students_path %>

app/views/tweets/index.html.erb
welcome